name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "angular-contact-app"
      IMAGE_TAG: "v1"
      CONTAINER_NAME: "angular-contact-container"

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Angular App
      - name: Build Angular App
        working-directory: ./angular-contact-list  # Ensure this is correct
        run: |
          npm install
          npm run build

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      # Step 5: Run Trivy Scan
      - name: Run Trivy Scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --severity HIGH,CRITICAL --no-progress --format table -o trivy-report.html || true

      # Step 6: Docker Cleanup (optional)
      - name: Docker Cleanup
        run: |
          docker rmi ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} || true
