name: Trivy Image Scan

on:
  push:
    branches:
      - image-scanner  
  pull_request:
    branches:
      - image-scanner  

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull Docker Image
      - name: Pull Docker Image
        run: |
          docker pull bhargav5523/node-app:v1

      # Step 2: Run Trivy Scan on the Pulled Image
      - name: Run Trivy Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image bhargav5523/node-app:v1 \
            --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL \
            --no-progress \
            --format table \
            -o /app/trivy-report.html || true

      # Step 3: Upload Trivy Report
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: ./trivy-report.html
