name: Image Build & Scan

on:
  push:
    branches:
      - image-scanner  
  pull_request:
    branches:
      - image-scanner  

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "angular-contact-app"
      IMAGE_TAG: "latest"

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      # Step 3: Run Trivy Scan (all severities)
      - name: Run Trivy Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL \
            --no-progress \
            --format table \
            -o /app/trivy-report.html || true

      # Step 4: Upload Trivy Report
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: ./trivy-report.html
