name: CI Pipeline

on:
  push:
    branches:
      - image-scanner  
  pull_request:
    branches:
      - image-scanner  

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "angular-contact-app"
      IMAGE_TAG: "latest"
      CONTAINER_NAME: "angular-contact-container"

    steps:
      # Step 1: Checkout code from the image-scanner branch
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: image-scanner  # Checkout the image-scanner branch

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Angular App
      - name: Build Angular App
        working-directory: ./src  # Correct path to your angular app
        run: |
          npm install
          npm run build

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      # Step 5: Run Trivy Scan
      - name: Run Trivy Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --severity HIGH,CRITICAL \
            --no-progress \
            --format table \
            -o /app/trivy-report.html || true

      # Step 6: Confirm Trivy Report Exists
      - name: Confirm Trivy Report
        run: |
          if [[ -f trivy-report.html ]]; then
            echo "✅ Trivy report created."
          else
            echo "❌ Trivy report not found."
            exit 1
          fi

      # Step 7: Upload Trivy Report
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: ./trivy-report.html

      # Step 8: Docker Cleanup (optional)
      - name: Docker Cleanup
        run: |
          docker rmi ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} || true
